languageCode = "es"
languageName = "Español"
weight = 1
title = "salocinvh"

[params]
  displayName = "ES"
  isoCode = "es"
  rtl = false
  dateFormat = "2 January 2006"
  description = "CV - Nicolás Vargas H."

[params.author]
  name = "comms"
  email = "salocinvh@proton.me"
  headline = "Nicolás Vargas H."
  image = "img/caracortada.png"
